# Generated by Django 3.1.5 on 2021-01-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='published_at',
            new_name='posted',
        ),
    ]
