# Generated by Django 3.1.5 on 2021-01-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210116_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='salary_max',
            new_name='salary_from',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='salary_min',
            new_name='salary_to',
        ),
    ]
