# Generated by Django 3.1.5 on 2021-01-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210116_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='title',
        ),
    ]
