# Generated by Django 3.1.5 on 2021-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210122_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(default='https://place-hold.it/100x60'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.URLField(default='https://place-hold.it/100x60'),
        ),
    ]
