# Generated by Django 3.1.5 on 2021-01-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20210124_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='written_cover_letter',
            new_name='cover_letter',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='written_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='written_username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(upload_to='speciality_images'),
        ),
    ]
