# Generated by Django 3.1.5 on 2021-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20210129_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
    ]
